language: erlang
script: rebar --config=rebar.dev.config get-depts && rebar --config=rebar.dev.config compile && rebar --config=rebar.dev.config skip_deps=true eunit
otp_release:
  - R15B03
  - R15B02
  - R15B01
  - R15B
